# Generated by Django 5.1.3 on 2025-01-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кількість'),
        ),
    ]
