# Generated by Django 5.1.3 on 2025-02-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_like_likeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кількість'),
        ),
    ]
