# Generated by Django 5.1.3 on 2025-01-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upon receipt', 'При отриманні'), ('Full subscription', 'Повна передоплата')], default='upon receipt'),
        ),
    ]
