# Generated by Django 5.1.3 on 2025-02-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'в обробці'), ('confirmed', 'підтверджено'), ('cancelled', 'скасовано')], default='pending'),
        ),
    ]
