# Generated by Django 5.1.3 on 2025-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'В очікуванні'), ('paid', 'Оплачено'), ('failed', 'Скасовано')], default='pending'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('confirmed', 'підтверджено'), ('cancelled', 'скасовано')], default='created'),
        ),
    ]
