# Generated by Django 5.1.3 on 2025-03-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upon receipt', 'При отриманні'), ('Full subscription', 'Передоплата')], default='upon receipt'),
        ),
    ]
