# Generated by Django 5.1.3 on 2025-01-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_type_of_flavor_product_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_flavor',
            field=models.TextField(choices=[('floral', 'Квітковий'), ('fruity', 'Фруктовий'), ('woody', 'Деревний'), ('chypre', 'Шипровий'), ('oriental', 'Східний'), ('citrus', 'Цитрусовий'), ('spicy', 'Пряний'), ('marine', 'Морський'), ('vanilla', 'Ванільний')], default='-', verbose_name='Аромат'),
        ),
    ]
