# Generated by Django 5.1.3 on 2025-01-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_flavor',
            field=models.TextField(default='-', verbose_name='Аромат'),
        ),
    ]
