# Generated by Django 5.1.3 on 2025-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_type_flavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аромат')),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_flavor',
        ),
        migrations.AddField(
            model_name='product',
            name='type_flavor',
            field=models.ManyToManyField(related_name='flavors', to='products.typeflavor'),
        ),
    ]
