# Generated by Django 5.1.3 on 2025-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_typeflavor_remove_product_type_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_flavor',
            field=models.ManyToManyField(related_name='flavors', to='products.typeflavor', verbose_name='Аромат'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
    ]
