# Generated by Django 5.1.3 on 2025-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_available_alter_product_type_flavor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість вподобань'),
        ),
    ]
