# Generated by Django 5.1.3 on 2025-03-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
